Repository MoonchildProductions/UXP, pull requests merged in 2018-07, with the labels that each got.

#580 Fix typo in a comment - performance.dtd
  devtools/client/locales/en-US/performance.dtd
Labels: Not an Issue

#590 [PALEMOON] DevTools - remove unused items from browser.dtd
  application/palemoon/locales/en-US/chrome/browser/browser.dtd
Labels: String Changes

#608 Merge branch js modules basic
  dom/base/nsScriptLoader.cpp
  dom/base/nsScriptLoader.h
  js/src/builtin/Iterator.js
  js/src/builtin/Module.js
  js/src/builtin/ModuleObject.cpp
  js/src/builtin/ModuleObject.h
  js/src/builtin/SelfHostingDefines.h
  js/src/jit-test/modules/empty.js
  js/src/jit-test/modules/export-circular-nonexisting-binding-1.js
  js/src/jit-test/modules/export-circular-nonexisting-binding-2.js
  js/src/jit-test/modules/export-star-circular-1.js
  js/src/jit-test/modules/export-star-circular-2.js
  js/src/jit-test/tests/basic/bug1220766.js
  js/src/jit-test/tests/modules/bug-1320993.js
  js/src/jit-test/tests/modules/export-circular-nonexisting-binding.js
  js/src/jit-test/tests/modules/export-star-cannot-rescue-missing-export.js
  js/src/jit-test/tests/modules/export-star-circular-dependencies.js
  js/src/jit-test/tests/modules/import-namespace.js
  js/src/jit/InlinableNatives.h
  js/src/jit/MCallOptimize.cpp
  js/src/jsiter.cpp
  js/src/jsiter.h
  js/src/vm/EnvironmentObject.cpp
  js/src/vm/SelfHosting.cpp
  modules/libpref/init/all.js
Labels: C: Javascript, Enhancement

#609 Fix typos in comments - memory.properties
  devtools/client/locales/en-US/memory.properties
Labels: Not an Issue

#619 Pale Moon: Fix positioning of caption buttons in application-drawn ti…
  application/palemoon/base/content/browser.xul
  application/palemoon/themes/osx/browser.css
Labels: App: Pale Moon, C: Theme, C: UI, Platform: Mac OS X, Theme Changes

#652 Make document.domain non-nullable
  dom/html/nsHTMLDocument.cpp
  dom/webidl/HTMLDocument.webidl
Labels: Low Risk

#655 [PALEMOON] Enable update prefs in Official branding for Linux
  application/palemoon/branding/official/pref/palemoon-branding.js
Labels: App: Pale Moon, C: Installer/Updater, Platform: Linux

#661 [PALEMOON] Places - remove unused @param from controller.js
  application/palemoon/components/places/content/controller.js
Labels: Not an Issue
