Repository MoonchildProductions/UXP, pull requests merged in 2018-04, with the labels that each got.

#94 Fix Value::isGCThing footgun, stop returning true for NullValue
  dom/xhr/XMLHttpRequestWorker.cpp
  js/public/CallArgs.h
  js/public/Proxy.h
  js/public/TraceKind.h
  js/public/Value.h
  js/src/builtin/TestingFunctions.cpp
  js/src/gc/Barrier.cpp
  js/src/gc/Barrier.h
  js/src/gc/Marking.cpp
  js/src/gc/Marking.h
  js/src/jit/CodeGenerator.cpp
  js/src/jit/JitFrames.cpp
  js/src/jit/Lowering.cpp
  js/src/jit/arm/MacroAssembler-arm.cpp
  js/src/jit/arm/MacroAssembler-arm.h
  js/src/jit/arm64/MacroAssembler-arm64.h
  js/src/jit/mips32/MacroAssembler-mips32.cpp
  js/src/jit/mips32/MacroAssembler-mips32.h
  js/src/jit/mips64/MacroAssembler-mips64.cpp
  js/src/jit/mips64/MacroAssembler-mips64.h
  js/src/jit/x64/MacroAssembler-x64.h
  js/src/jit/x86/MacroAssembler-x86.cpp
  js/src/jit/x86/MacroAssembler-x86.h
  js/src/jscompartmentinlines.h
  js/src/jsfriendapi.h
  js/src/jsfun.h
  js/src/jsscript.cpp
  js/src/vm/ProxyObject.cpp
  js/xpconnect/src/XPCVariant.cpp
  xpcom/base/nsCycleCollector.cpp
  xpcom/base/nsCycleCollectorTraceJSHelpers.cpp
Labels: Component: Javascript, High Risk

#181 Fix GCC -Wreorder warnings.
  netwerk/protocol/http/nsHttpHandler.h
Labels: Component: Build System

#223 Use -1 instead of 0 to indicate absent glxtest_pipe fd
  widget/GfxInfoX11.cpp
Labels: Platform: Linux

#273 [PALEMOON] [frontend vs backend] Fix "Permissions Manager" and permissions
  application/palemoon/app/profile/palemoon.js
  application/palemoon/base/content/browser-fullScreen.js
  application/palemoon/base/content/browser-plugins.js
  application/palemoon/base/content/browser.js
  application/palemoon/base/content/pageinfo/pageInfo.js
  application/palemoon/base/content/pageinfo/permissions.js
  application/palemoon/base/content/urlbarBindings.xml
  application/palemoon/components/nsBrowserGlue.js
  application/palemoon/components/preferences/aboutPermissions.js
  application/palemoon/components/preferences/aboutPermissions.xul
  application/palemoon/components/preferences/advanced.js
  application/palemoon/components/preferences/cookies.js
  application/palemoon/components/preferences/handlers.xml
  application/palemoon/components/preferences/jar.mn
  application/palemoon/components/preferences/permissions.js
  application/palemoon/components/preferences/permissions.xul
  application/palemoon/components/preferences/security.js
  application/palemoon/locales/en-US/chrome/browser/browser.properties
  application/palemoon/locales/en-US/chrome/browser/preferences/aboutPermissions.dtd
  application/palemoon/locales/en-US/chrome/browser/preferences/permissions.dtd
  application/palemoon/locales/en-US/chrome/browser/preferences/preferences.properties
  application/palemoon/modules/webrtcUI.jsm
  application/palemoon/themes/linux/Push-16.png
  application/palemoon/themes/linux/Push-64.png
  application/palemoon/themes/linux/browser.css
  application/palemoon/themes/linux/jar.mn
  application/palemoon/themes/linux/notification-16.png
  application/palemoon/themes/linux/notification-64.png
  application/palemoon/themes/linux/preferences/aboutPermissions.css
  application/palemoon/themes/linux/web-notifications-icon.svg
  application/palemoon/themes/linux/web-notifications-tray.svg
  application/palemoon/themes/osx/Push-16.png
  application/palemoon/themes/osx/Push-64.png
  application/palemoon/themes/osx/browser.css
  application/palemoon/themes/osx/jar.mn
  application/palemoon/themes/osx/notification-16.png
  application/palemoon/themes/osx/notification-64.png
  application/palemoon/themes/osx/preferences/aboutPermissions.css
  application/palemoon/themes/osx/web-notifications-icon.svg
  application/palemoon/themes/osx/web-notifications-tray.svg
  application/palemoon/themes/windows/Push-16.png
  application/palemoon/themes/windows/Push-64.png
  application/palemoon/themes/windows/browser.css
  application/palemoon/themes/windows/jar.mn
  application/palemoon/themes/windows/notification-16.png
  application/palemoon/themes/windows/notification-64.png
  application/palemoon/themes/windows/preferences/aboutPermissions.css
  application/palemoon/themes/windows/web-notifications-icon.svg
  application/palemoon/themes/windows/web-notifications-tray.svg
Labels: String Changes, Theme Changes, Verification Needed

#281 [PALEMOON] [DevTools] Storage inspector throws "AddonPathService.mapURIToAddonId is not a function" when url changes
  toolkit/mozapps/extensions/AddonPathService.cpp
  toolkit/mozapps/extensions/amIAddonPathService.idl
  toolkit/mozapps/extensions/internal/XPIProvider.jsm
  toolkit/mozapps/extensions/test/xpcshell/test_mapURIToAddonID.js
Labels: Component: Extensions, Verification Needed
